In [4]:
import rasterio
from rasterio import merge
import numpy as np
import os
data_pkg_path = '../data'
srtm_dir = 'srtm'
srtm_path = os.path.join(data_pkg_path, 'srtm')
all_files = os.listdir(srtm_path)
dataset_list = []
for file in all_files:
    path = os.path.join(srtm_path, file)
    dataset_list.append(rasterio.open(path))
merged_result = merge.merge(dataset_list)
merged_data = merged_result[0]
print(merged_data)

[[[  4916   4926   4931 ...   5098   5089 -32768]
  [  4919   4932   4928 ...   5075   5069 -32768]
  [  4919   4928   4935 ...   5055   5048 -32768]
  ...
  [   364    364    362 ...   1930   1944 -32768]
  [   360    359    357 ...   1930   1942 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]]]


In [5]:
max_elev = np.max(merged_data)
print(max_elev)

8748
